module.exports = {
  main: {
    ".1c": "1C Enterprise",
    ".4th": "Forth",
    ".abap": "ABAP",
    ".ada": "Ada",
    ".adb": "Ada",
    ".ads": "Ada",
    ".ahk": "AutoHotkey",
    ".asm": "Assembly",
    ".asp": "ASP",
    ".aspx": "ASP.NET",
    ".awk": "Awk",
    ".bas": "BASIC",
    ".bat": "Batch",
    ".bf": "Brainfuck",
    ".bib": "BibTeX",
    ".bsh": "BeanShell",
    ".c": "C",
    ".cbl": "COBOL",
    ".cc": "C++",
    ".clj": "Clojure",
    ".cljs": "ClojureScript",
    ".cls": "Apex",
    ".cmake": "CMake",
    ".coffee": "CoffeeScript",
    ".command": "Shell",
    ".cpp": "C++",
    ".cs": "C#",
    ".csh": "C Shell",
    ".css": "CSS",
    ".cu": "CUDA",
    ".d": "D",
    ".dart": "Dart",
    ".dfy": "Dafny",
    ".el": "Emacs Lisp",
    ".elm": "Elm",
    ".erb": "ERB",
    ".erl": "Erlang",
    ".ex": "Elixir",
    ".exs": "Elixir",
    ".f": "Fortran",
    ".f90": "Fortran",
    ".fish": "Fish",
    ".fs": "F#",
    ".fsi": "F#",
    ".fsscript": "F#",
    ".gml": "GameMaker",
    ".go": "Go",
    ".gradle": "Gradle",
    ".groovy": "Groovy",
    ".h": "C Header",
    ".haml": "Haml",
    ".handlebars": "Handlebars",
    ".haskell": "Haskell",
    ".hbs": "Handlebars",
    ".hh": "C++",
    ".hlsl": "HLSL",
    ".hs": "Haskell",
    ".html": "HTML",
    ".hx": "Haxe",
    ".idl": "IDL",
    ".ini": "INI",
    ".ipynb": "Jupyter Notebook",
    ".java": "Java",
    ".jl": "Julia",
    ".js": "JavaScript",
    ".jsx": "Javascript (JSX)",
    ".jsp": "Java Server Pages",
    ".kt": "Kotlin",
    ".kts": "Kotlin Script",
    ".l": "Lex",
    ".less": "Less",
    ".lhs": "Literate Haskell",
    ".lisp": "Lisp",
    ".logtalk": "Logtalk",
    ".lua": "Lua",
    ".m": "Objective-C",
    ".mak": "Makefile",
    ".markdown": "Markdown",
    ".mat": "MATLAB",
    ".ml": "OCaml",
    ".mli": "OCaml Interface",
    ".mm": "Objective-C++",
    ".mjs": "JavaScript",
    ".mustache": "Mustache",
    ".nix": "Nix",
    ".nim": "Nim",
    ".nu": "Nu",
    ".p6": "Raku",
    ".pas": "Pascal",
    ".php": "PHP",
    ".pl": "Perl",
    ".pm": "Perl Module",
    ".pony": "Pony",
    ".ps1": "PowerShell",
    ".py": "Python",
    ".pyw": "Python",
    ".qml": "QML",
    ".r": "R",
    ".rake": "Ruby",
    ".rb": "Ruby",
    ".re": "ReasonML",
    ".res": "ReScript",
    ".rkt": "Racket",
    ".rs": "Rust",
    ".sass": "Sass",
    ".scala": "Scala",
    ".scm": "Scheme",
    ".scss": "SCSS",
    ".sh": "Shell",
    ".sml": "Standard ML",
    ".sol": "Solidity",
    ".sql": "SQL",
    ".ss": "Scheme",
    ".styl": "Stylus",
    ".swift": "Swift",
    ".tcl": "Tcl",
    ".tex": "LaTeX",
    ".ts": "TypeScript",
    ".tsx": "Typescript (TSX)",
    ".vala": "Vala",
    ".vb": "VB.NET",
    ".vbs": "VBScript",
    ".vue": "Vue",
    ".wat": "WebAssembly Text",
    ".wasm": "WebAssembly",
    ".xsl": "XSLT",
    ".zig": "Zig",
  },
  other: {
    ".toml": "TOML",
    ".md": "Markdown",
    ".txt": "Text",
    ".rst": "reStructuredText",
    ".adoc": "AsciiDoc",
    ".json": "JSON",
    ".yml": "YAML",
    ".yaml": "YAML",
    ".xml": "XML",
    ".csv": "CSV",
  },
};
